name: Integration Tests
on: [push, pull_request]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the project
        run: uv sync --all-extras
      - name: Start Gateway
        run: uv run fastapi dev fast_priority_queue/app.py --host 0.0.0.0 --port 8001 &
      - name: Start API
        run: uv run fastapi dev examples/end2end/app.py --host 0.0.0.0 --port 8010 &
      - name: Start worker
        run: uv run rq worker high low &
      - name : Run integration tests
        run: uv run pytest  tests/integration/
