name: Python Unit Tests

on: [push, pull_request]

jobs:
  build:
    name: unit-tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version:
          - "3.12"
        os: 
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the project
        run: uv sync --all-extras
      - name: Run tests
        run: uv run pytest 
